import subprocess
import re
import tkinter as tk
from tkinter import messagebox


#Get the default gateway IP
def get_gateway_ip():
    result = subprocess.check_output("ip route",shell=True).decode()
    match = re.search(r"default via (\S+)",result)
    return match.group(1) if match else none


# Ping the gateway and a safe public IP to pupulate the ARP table passively. 
def generate_arp_entries_with_nmap(subnet="10.0.0.0/24"):
    try:
        # Run Nmap to discover devices
        nmap_cmd = f"nmap -sn {subnet}"
        nmap_output = subprocess.check_output(nmap_cmd, shell=True).decode()

        #Extract IP addresses from Nmap output
        ip_list = []
        for line in nmap_output.splitlines():
            if "Nmap scan report for" in line:
                ip = line.split()[-1]
                ip_list.append(ip)

        # Ping each IP once to populate ARP cache
        for ip in ip_list:
            subprocess.run(["ping","-c","1",ip],stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
    
    except Exception as e:
        print(f"Error generating ARP entries: {e}")
    

# CHeck if any IP other than the gateway shares its MAC address - possible spoof
def get_arp_table():
    #to understand this function, consider the example output of arp -a command on linux: 
    # ? (10.0.0.213) at f1:11:de:1d:9a:d9 [ether] on eth0
    # the first step is to run the arp -a command using the subprocess library and store the output in the result variable which will be a dictionary
    # the second step is to run the the rejex findall method(re.findall) to extract only the ip address and the mac address of every line
    # generated by arp -a. since we have two data elements we need to extract, it means we will need the rejex to groups
    #the first group (\d+\.\d+\.\d+\.\d+) enclosed in brackets represent all possible ip address formats
    #the second group ([A-Fa-f0-9:-]{17}) enclosed in brackets represent all possible mac address formats
    #all remaining characters in the output from arp -a are simply ignored
    result = subprocess.check_output("arp -a",shell=True).decode() 
    arp_entries = re.findall(r"\((\d+\.\d+\.\d+\.\d+)\)\s+.*?([A-Fa-f0-9:-]{17})",result,re.IGNORECASE)
    return {ip:mac.lower() for ip,mac in arp_entries} #making a dictionary where key is ip and value is MAC address

#CHeck if any IP other than the gateway shares its MAC address - possible spoof
def check_arp_spoofing():
    #We need to clear any cached arp table prior,otherwise the results could be wrong.
    print("clearing arp cache...")
    subprocess.run(["sudo", "ip", "-s", "-s", "neigh", "flush", "all"], check=True)
    print("arp cache cleared.")
    print("Generating arp table...")
    generate_arp_entries_with_nmap()
    print("arp table complete.")
    print("getting gateway ip...")
    gateway_ip = get_gateway_ip()
    if not gateway_ip:
        messagebox.showerror("Error", "Could not detect gateway IP.")
        return False
    print("getting gateway ip complete")
    print("getting arp table...")
    arp_table = get_arp_table()
    print("arp table stored in variable...",arp_table)
    print("getting gateway mac address...")
    gateway_mac = arp_table.get(gateway_ip)
    if not gateway_mac:
        messagebox.showerror("Error", "Could not detect gateway IP.")
        return False
    print("getting mac address complete")
    for ip,mac in arp_table.items():
        if ip != gateway_ip and mac == gateway_mac:
            print("spoofing detected...")
            return True #Spoofing likely
    print("spoofing not detected.")
    return False # All good

# GUI logic
def on_button_click():
    spoofed = check_arp_spoofing()
    if spoofed:
        button.config(bg="red",text="ARP Spoofing Detected!")
        messagebox.showwarning("Warning", "ARP Spoofing Detected!")
    else:
        button.config(bg="green",text="No Spoofing Detected!")

#Tkinter setup
root = tk.Tk()
root.title("ARP Spoofing Detector")
root.geometry("300x150")

button = tk.Button(root, text="Check Network", command=on_button_click, height=3,width=25)
button.pack(pady=40)

root.mainloop()
